/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainTest */

#ifndef _Included_mainTest
#define _Included_mainTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainTest
 * Method:    simpleNN
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_mainTest_simpleNN
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
