/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mainTest3 */

#ifndef _Included_mainTest3
#define _Included_mainTest3
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mainTest3
 * Method:    simpleNN
 * Signature: (Ljava/util/Map;)Z
 */
JNIEXPORT jboolean JNICALL Java_mainTest3_simpleNN
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
